image: "thlmylab/swakkd:stable"

variables:
  DOMAIN: "edu.k8s.th-luebeck.dev"

stages:
- prepare
- build
- deploy
- destroy

credentials:
  stage: prepare
  script:
  - kubectl delete secret gitlab-registry-$CI_PROJECT_ID || true
  - >
    kubectl create secret docker-registry gitlab-registry-$CI_PROJECT_ID
    --docker-server=$CI_REGISTRY
    --docker-username=image-registry
    --docker-password=$CI_REGISTRY_TOKEN

app-img:
  stage: build
  image: docker:dind
  services: ["docker:dind"]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/app-$CI_COMMIT_REF_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/app-$CI_COMMIT_REF_NAME:latest

app:
  stage: deploy
  script:
  - mo deploy/app-dep.yaml | kubectl delete -f - || true
  - mo deploy/app-dep.yaml | kubectl apply -f -
  - mo deploy/app-svc.yaml | kubectl apply -f -

ingress:
  stage: deploy
  when: manual
  script:
  - HOST=uber-$CI_PROJECT_ID.$DOMAIN mo deploy/project-ing.yaml | kubectl apply -f -
