apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ CI_COMMIT_REF_NAME }}-app
spec:
  selector:
    matchLabels:
      app: {{ CI_COMMIT_REF_NAME }}-app
  template:
    metadata:
      labels:
        app: {{ CI_COMMIT_REF_NAME }}-app
    spec:
      imagePullSecrets:
      - name: gitlab-registry-{{ CI_PROJECT_ID }}
      containers:
      - name: app
        image: {{ CI_REGISTRY_IMAGE }}/app-{{ CI_COMMIT_REF_NAME }}:latest
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"